export enum AuthActionTypes {
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAIL = 'REGISTER_FAIL',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAIL = 'LOGIN_FAIL',
    LOGOUT = 'LOGOUT',
}

export enum MessageActionTypes {
    SET_MESSAGE = 'SET_MESSAGE',
    CLEAR_MESSAGE = 'CLEAR_MESSAGE',
}
